import { Metadata } from "next";
import React from "react";
import Navbar from "@/app/components/Layouts/Navbar";
import ScreenWrapper from "@/app/components/Layouts/ScreenWrapper";
import Appointment from "@/app/components/forms/Appointment";
import Header from "../Header";
import store from "@/store/store";
import { API_URL } from "@/utils/constants";
import axios from "axios";

import { setUserData } from "@/store/slices/authSlice";

interface ParamsType {
  // Define the structure of params object
  landingpage: string;
}

interface SearchParamsType {
  // Define the structure of searchParams object
}

async function page({
  params,
  searchParams,
}: {
  params: ParamsType;
  searchParams: SearchParamsType;
}) {
  let businessLandingPage = null;
  const options = {
    method: "post",
    url: API_URL + "slug",
    headers: {
      Accept: "*/*",
      "Content-Type": "application/json",
      cache: "no-store",
    },
    data: {
      slug: params.landingpage,
    },
  };

  try {
    const response = await axios(options);
    businessLandingPage = response.data;
  } catch (error) {
    console.error("error00000:" + error);
  }

  const businessData = businessLandingPage?.data;
  const title = businessData?.businessName;
  const about = businessData?.about;
  const address = businessData?.address;

  if (businessData) {
    store.dispatch(setUserData(businessData));
  }

  if (businessData) {
    return (
      <main className="flex bg-background flex-col w-[100vw] min-h-[120vh]">
        <div className="relative h-auto w-full  ">
          <ScreenWrapper>
            <Navbar />
            <Header title={title} about={about} address={address} />
            <Appointment businessData={businessData} />
          </ScreenWrapper>
        </div>
      </main>
    );
  } else {
    return null;
  }
}

export default page;

export const metadata: Metadata = {
  title: "Appointify - Book Your Appointment",
  description:
    "your ultimate tool for quick, concise summaries generated by AI!, Say goodbye to long hours of reading and let Briefology empower you with the information you need, when you need it.",
  icons: {
    icon: "/reading.webp",
  },
};
