import { Metadata } from "next";
import React from "react";
import Header from "./Header";
import Navbar from "@/app/components/Layouts/Navbar";
import ScreenWrapper from "@/app/components/Layouts/ScreenWrapper";
import MoreSection from "./MoreSection";
import { API_URL } from "@/utils/constants";
import axios from "axios";
import store from "@/store/store";
import { setUserData } from "@/store/slices/authSlice";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import PageSection from "./PageSection";
interface ParamsType {
  // Define the structure of params object
  landingpage: string;
}

interface SearchParamsType {
  // Define the structure of searchParams object
}

async function page({
  params,
  searchParams,
}: {
  params: ParamsType;
  searchParams: SearchParamsType;
}) {
  return (
    <main className="flex bg-background flex-col w-[100vw] min-h-[100vh] ">
      <PageSection landingpage={params.landingpage} />
    </main>
  );
}

export default page;

export const metadata: Metadata = {
  title: "Breifology - Your Gateway to Quick Knowledge",
  description:
    "your ultimate tool for quick, concise summaries generated by AI!, Say goodbye to long hours of reading and let Briefology empower you with the information you need, when you need it.",
  icons: {
    icon: "/reading.webp",
  },
};
