import { Metadata } from "next";
import React from "react";
import Header from "./Header";
import Navbar from "@/app/components/Layouts/Navbar";
import ScreenWrapper from "@/app/components/Layouts/ScreenWrapper";
import MoreSection from "./MoreSection";

interface ParamsType {
  // Define the structure of params object
  landingpage: string;
}

interface SearchParamsType {
  // Define the structure of searchParams object
}

function page({
  params,
  searchParams,
}: {
  params: ParamsType;
  searchParams: SearchParamsType;
}) {
  const title = params.landingpage;
  const about =
    "Welcome to Assemble, your premier unisex salon nestled in the vibrant Adajan area of Surat. Our salon is a sanctuary where style meets sophistication, offering a diverse range of cutting-edge services tailored to both men and women";
  const address = "abc,near shakti nagar,adajan,pal,340949";

  return (
    <main className="flex bg-background flex-col w-[100vw] min-h-[100vh] ">
      <div className="relative h-auto w-full  ">
        <ScreenWrapper>
          <Navbar />
          <Header title={title} about={about} address={address} />
          <MoreSection />
        </ScreenWrapper>
      </div>
    </main>
  );
}

export default page;

export const metadata: Metadata = {
  title: "Breifology - Your Gateway to Quick Knowledge",
  description:
    "your ultimate tool for quick, concise summaries generated by AI!, Say goodbye to long hours of reading and let Briefology empower you with the information you need, when you need it.",
  icons: {
    icon: "/reading.webp",
  },
};
